# Generated by Django 3.1.2 on 2021-03-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImageLink',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='productPrice',
            field=models.BigIntegerField(),
        ),
    ]
