# Generated by Django 3.1.2 on 2021-03-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=30)),
                ('productImageLink', models.CharField(max_length=30)),
                ('productBrand', models.CharField(max_length=30)),
                ('productPrice', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
